# Generated by Django 5.1.1 on 2024-09-19 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('appointment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('test_timing', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('hashed_password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone_number', models.CharField(max_length=15)),
                ('contact_relationship', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('clinic_or_hospital_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='MentalHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood_swing', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], max_length=3)),
                ('optimisim', models.CharField(choices=[('1 From 10', '1 From 10'), ('2 From 10', '2 From 10'), ('3 From 10', '3 From 10'), ('4 From 10', '4 From 10'), ('5 From 10', '5 From 10'), ('6 From 10', '6 From 10'), ('7 From 10', '7 From 10'), ('8 From 10', '8 From 10'), ('9 From 10', '9 From 10')], max_length=20)),
                ('euphoric', models.CharField(choices=[('Seldom', 'Seldom'), ('Most-Often', 'Most-Often'), ('Usually', 'Usually'), ('Sometimes', 'Sometimes')], max_length=20)),
                ('exhausted', models.CharField(choices=[('Seldom', 'Seldom'), ('Usually', 'Usually'), ('Most-Often', 'Most-Often'), ('Sometimes', 'Sometimes')], max_length=20)),
                ('concentration', models.CharField(choices=[('1 From 10', '1 From 10'), ('2 From 10', '2 From 10'), ('3 From 10', '3 From 10'), ('4 From 10', '4 From 10'), ('5 From 10', '5 From 10'), ('6 From 10', '6 From 10'), ('7 From 10', '7 From 10'), ('8 From 10', '8 From 10'), ('9 From 10', '9 From 10')], max_length=20)),
                ('sexual_activity', models.CharField(choices=[('1 From 10', '1 From 10'), ('2 From 10', '2 From 10'), ('3 From 10', '3 From 10'), ('4 From 10', '4 From 10'), ('5 From 10', '5 From 10'), ('6 From 10', '6 From 10'), ('7 From 10', '7 From 10'), ('8 From 10', '8 From 10'), ('9 From 10', '9 From 10')], max_length=20)),
                ('aggressive_response', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], max_length=3)),
                ('suicidal_thoughts', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], max_length=3)),
                ('authority_respect', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], max_length=3)),
                ('sadness', models.CharField(choices=[('Seldom', 'Seldom'), ('Usually', 'Usually'), ('Most-Often', 'Most-Often'), ('Sometimes', 'Sometimes')], max_length=20)),
                ('prediction', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
